music/urls.py
from django.conf.urls import url
from . import views

app_name='music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name="index"),
    # /music/71/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail')
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
	artist=models.CharField(max_length=250)
	album_title=models.CharField(max_length=250)
	genre=models.CharField(max_length=250)
	album_logo=models.CharField(max_length=1000)
	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	album=models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type=models.CharField(max_length=10)
	song_title=models.CharField(max_length=250)
	is_favorite=models.BooleanField(default=False)
	def __str__(self):
		return self.song_title

music/views.py
from django.views import generic
from .models import Album

class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DeleteView):
    model = Album
    template_name = 'music/detail.html'

music/templates/music/base.html
<!doctype html>
<!DOCTYPE html>
<html>
<head>
    <title>Title</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/main.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav>
            <!-- <h2 href="www.google.com">Sumit</h2> -->
            <a href="#">Sumit</a>
            <ul>
                <li><a href="/music/">Albums</a></li>
                <li><a href="#">Songs</a></li>
                <li class='fright'><a href="#">logout</a></li>
                <li class='fright'><a href="#">addAlbum</a></li>
            </ul>
        </nav>
    </header>

{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block body %}

<img src='{{ album.album_logo }}' width='250'>
<br>
<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

<ul>
	{% for song in album.song_set.all %}
	<li>{{ song.song_title }} - {{ song.file_type }}</li>
	{% endfor %}
</ul>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
{% if object_list %}

		{% for album in object_list %}
        <!-- <div class="albums">
        <a href="{% url 'music:detail' album.id %}">
            <div>
                <img src='{{ album.album_logo }}' width='250'><br>
                <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
                <li>{{ album.album_title }}</li>
            </div>
        </a>
        </div> -->
        <div class="col-sm-4 col-lg-2 albums">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo}}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                        </div>
                    </div>
                </div>
        {% endfor %}

{% else %}
	<h2>You don't have any album</h2>
{% endif %}

{% endblock %}